name: Update blocklist
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone blocklist repo
        uses: actions/checkout@v4
        with:
          repository: n00bady/bluam

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Change to blocklist repo and install dependencies
        run: |
          cd bluam
          go mod tidy
          go run build .

      - name: Execute blocklist
        run: ./bluam/bluam

      - name: Change files
        run: |
          rm -rf *.txt
          mv bluam/dns/merged/*.txt .
          rm -rf bluam

      - name: Check if there's any update in the git files
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.name 'DiegoRamil'
            git config --global user.email 'nxquumodding@users.noreply.github.com'
            git commit -am "[AUTO] Updating blocker list"
            git push
          else
            echo "There was no changes to commit"

